import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from "@/contexts/AuthContext";
import { LinkSunoAccount } from "@/components/suno/LinkSunoAccount";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
export const Index = () => {
    const { user } = useAuth();
    const isSigningUp = new URLSearchParams(window.location.search).get('signup') === 'true';
    // Only show linking component if user is signing up
    if (isSigningUp) {
        return (_jsx("div", { className: "min-h-screen pt-24 pb-12", children: _jsx("div", { className: "onus-container", children: _jsx(LinkSunoAccount, {}) }) }));
    }
    // Regular landing page content
    return (_jsx("div", { className: "min-h-screen pt-24 pb-12", children: _jsx("div", { className: "onus-container", children: _jsxs("div", { className: "max-w-4xl mx-auto space-y-12", children: [_jsxs("div", { className: "text-center space-y-6 animate-fade-in", children: [_jsx("h1", { className: "text-5xl font-bold bg-gradient-to-r from-onus-purple via-onus-blue to-onus-pink bg-clip-text text-transparent", children: "Welcome to Onus" }), _jsx("p", { className: "text-xl text-muted-foreground max-w-2xl mx-auto", children: "Connect with musicians, share your music, and grow your audience. Join our community of passionate artists and creators." }), _jsxs("div", { className: "flex justify-center gap-4", children: [_jsx(Link, { to: "/explore", children: _jsx(Button, { size: "lg", variant: "default", children: "Explore Music" }) }), !user && (_jsx(Link, { to: "/?signup=true", children: _jsx(Button, { size: "lg", variant: "outline", children: "Join Now" }) }))] })] }), _jsxs("div", { className: "grid md:grid-cols-3 gap-8 py-12", children: [_jsxs("div", { className: "space-y-4 p-6 rounded-lg border bg-card text-card-foreground shadow-sm", children: [_jsx("h3", { className: "text-xl font-semibold", children: "Connect" }), _jsx("p", { className: "text-muted-foreground", children: "Find and collaborate with musicians who share your passion and vision." })] }), _jsxs("div", { className: "space-y-4 p-6 rounded-lg border bg-card text-card-foreground shadow-sm", children: [_jsx("h3", { className: "text-xl font-semibold", children: "Create" }), _jsx("p", { className: "text-muted-foreground", children: "Use AI-powered tools to compose, arrange, and produce your music." })] }), _jsxs("div", { className: "space-y-4 p-6 rounded-lg border bg-card text-card-foreground shadow-sm", children: [_jsx("h3", { className: "text-xl font-semibold", children: "Share" }), _jsx("p", { className: "text-muted-foreground", children: "Showcase your work and get feedback from the community." })] })] }), _jsxs("div", { className: "text-center py-12 space-y-6", children: [_jsx("h2", { className: "text-3xl font-bold", children: "Ready to make music?" }), _jsx("p", { className: "text-muted-foreground max-w-xl mx-auto", children: "Join our growing community of musicians and start creating today." }), !user && (_jsx(Link, { to: "/?signup=true", children: _jsx(Button, { size: "lg", className: "bg-onus-purple hover:bg-onus-purple/90", children: "Get Started" }) }))] })] }) }) }));
};
