import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Music2, Video } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { SunoPlayer } from "../SunoPlayer";
import { VideoEmbed } from "../VideoEmbed";
export const MusicianContent = ({ musician, isOwner }) => {
    return (_jsxs("div", { className: "mt-12 space-y-8", children: [_jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-12 gap-8", children: [_jsxs("div", { className: "lg:col-span-8 space-y-6", children: [_jsx(Card, { children: _jsxs(CardContent, { className: "p-6", children: [_jsxs("div", { className: "flex items-center gap-2 mb-6", children: [_jsx(Music2, { className: "h-5 w-5 text-muted-foreground" }), _jsx("h2", { className: "text-xl font-semibold", children: "Songs" })] }), _jsx(ScrollArea, { className: "h-[400px]", children: _jsx("div", { className: "space-y-4", children: musician.songs?.map((song) => (_jsxs("div", { className: "p-4 border rounded-lg space-y-2", children: [_jsx("h4", { className: "font-medium", children: song.title }), _jsx(SunoPlayer, { songId: song.url })] }, song.id))) }) })] }) }), _jsx(Card, { children: _jsxs(CardContent, { className: "p-6", children: [_jsxs("div", { className: "flex items-center gap-2 mb-6", children: [_jsx(Video, { className: "h-5 w-5 text-muted-foreground" }), _jsx("h2", { className: "text-xl font-semibold", children: "Videos" })] }), _jsx(ScrollArea, { className: "h-[400px]", children: _jsx("div", { className: "space-y-4", children: musician.videos?.map((video) => (_jsxs("div", { className: "p-4 border rounded-lg space-y-2", children: [_jsx("h4", { className: "font-medium", children: video.title }), _jsx(VideoEmbed, { video: video })] }, video.id))) }) })] }) })] }), _jsx("div", { className: "lg:col-span-4", children: _jsx(Card, { children: _jsxs(CardContent, { className: "p-6", children: [_jsx("h3", { className: "font-semibold mb-4", children: "About" }), musician.bio ? (_jsx("p", { className: "text-muted-foreground", children: musician.bio })) : (_jsx("p", { className: "text-muted-foreground italic", children: "No bio available" })), musician.musician_genres && musician.musician_genres.length > 0 && (_jsxs(_Fragment, { children: [_jsx("div", { className: "my-4 border-t" }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-3", children: "Genres" }), _jsx("div", { className: "flex flex-wrap gap-2", children: musician.musician_genres.map((mg, index) => (_jsx("span", { className: "px-3 py-1 bg-secondary rounded-full text-sm", children: mg.genre.name }, index))) })] })] }))] }) }) })] }), (!musician.songs?.length && !musician.videos?.length) && (_jsxs("div", { className: "text-center py-12", children: [_jsxs("div", { className: "flex justify-center space-x-4", children: [_jsx(Music2, { className: "h-12 w-12 text-muted-foreground" }), _jsx(Video, { className: "h-12 w-12 text-muted-foreground" })] }), _jsx("p", { className: "text-muted-foreground mt-4", children: "No content available" })] }))] }));
};
