// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfzdbtmmvlvnxtvcgxui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmemRidG1tdmx2bnh0dmNneHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NTI1MjEsImV4cCI6MjA1NzMyODUyMX0.T4n85VG-mfMHYK3mtDXs2-WLhBBuJuvMBCYLrgSRlPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: {
      getItem: (key) => localStorage.getItem(key),
      setItem: (key, value) => localStorage.setItem(key, value),
      removeItem: (key) => localStorage.removeItem(key)
    },
    autoRefreshToken: true,
    persistSession: true
  }
});
